version: '2'
services:
  arima:
    restart: unless-stopped
    image: arima:latest
    container_name: arima
    command: java -jar /arima/api-0.0.1.jar
    ports:
      - "9000:9000"
    depends_on:
      - rserve
    environment:
      - ARIMA_PORT=9000
      - RSERVE_PORT=6311
      - RSERVE_HOSTNAME=rserve
      - RSERVE_CODEPATH=/opt/arima/R
      - RSERVE_PRODUCTION=true

  arima-gui:
    restart: unless-stopped
    image: arima-gui:latest
    container_name: arima-gui
    ports:
      - "3000:3000"
    depends_on:
      - arima
      - rserve

  rserve:
    restart: unless-stopped
    image: rserve:latest
    container_name: rserve
    command: Rscript /opt/arima/R/runRserve.R
    ports:
      - "6311:6311"
